### ISSUE TITLE
Care to link my new extension since this one is no longer maintained?

### ISSUE THREAD

**Issue by flyx** [hansjhoffman/nova-nix#141]
First, thanks for writing this extension.

Since Nova has recently been updated with TreeSitter support, and this extension is marked as unmaintained, I have written a [new extension](https://github.com/flyx/nova-nix-suite) that utilizes TreeSitter. I also added language server support.

I humbly suggest linking to my extension in your Readme.

**Comment by rhoskal** [comment]
Absolutely. Nice work! I'll update the README to point towards your extension.
